FROM golang:1.21 AS build

WORKDIR /app
COPY .. .
RUN go mod download
RUN go mod verify
RUN CGO_ENABLED=0 GOOS=linux go build -o ports ./cmd/main.go

FROM alpine:latest AS runtime
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /app/ports .

CMD ["./ports"]