services:

  ports-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - FILE_PATH=./assets/ports.json

  redis:
    image: redis
    ports:
      - '6379:6379'